version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2.19-fpm
    working_directory: ~/spacetrack
    steps:
      - run: sudo apt-get update && sudo apt-get install -y ansible
      - checkout
      - run: cd ~/spacetrack && composer install
